- hosts: lamp
  tasks:

- name: install git
  yum: name={{ item }} state=installed
  with_items:
    - vim
    - zsh
    - git
    - zip
    - unzip

- name: install kernel
  yum: name={{ item }} state=installed
  with_items:
    -  kernel
    -  kernel-devel
    -  kernel-headers
    -  dkms
    -  gcc
    -  gcc-c++


- name : install httpd
  sudo : yes
  tasks:
  - name: install httpd
    yum: namme=httpd state=latest
  - name: start httpd
    yum: namme=httpd state=started enebled=yes
  notify:
  - httpd restart
  handlers:
  - name: httpd restart
  service: name=httpd state=restarted

- name: install php
  yum: name={{item}} state=latest enablerepo=remi,remi-php53
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-mcrypt
    - php-gd
    - php-opcache
    - php-fpm
    - php-pecl-xdebug
    - php-xml

  - name: install mysql repository
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present
  - name: install mysql
    yum: name=mysql-server state=latest
  - name=: mysql start / enable
    service: name=mysqld state=started enabled=yes